yarnPath: ".yarn/releases/yarn-berry.js"
packageExtensions:
  "@protobufjs/inquire@*":
    dependencies:
      long: "^4.0.0"
  "lnurl@*":
    dependencies:
      knex: "^0.21.1"
  "knex@*":
    dependencies:
      mysql: "^2.18.1"
  "sequelize@*":
    dependencies:
      mariadb: "^2.4.0"
